### ISSUE TITLE
Can't open Configurator on ESP32 Touchdown

### ISSUE THREAD

**Issue by Snowflake6** [sle118/FreeTouchDeck#2]
I've installed this fork on an ESP32 Touchdown that came preconfigured from Dustin Watts.  When I try to load the Configurator using Chrome, Edge, or Internet Explorer on a PC under Windows, I see the white screen with "Loading Configurator" and three chasing dots below it.  That screen never moves on from there to the configurator, it just sits there.
![image](https://user-images.githubusercontent.com/5349216/125992301-0aed612e-95ef-43bf-95f3-bfe643331af4.png)

Version is 0.9.11.

**Comment by sle118** [comment]
The development branch currently doesn't implement a configurator

**Comment by Snowflake6** [comment]
Thanks Sebastien... It might be worth putting a note in the main Readme to make that clear.
